
export const APPLY_FILTER = 'APPLY_FILTER'
export const FETCH = 'FETCH' 
export const STORE = 'STORE'
export const UPDATE_STATE = 'UPDATE_STATE'

// PRODUCTS

export const PRODUCTS_FETCH = 'PRODUCTS_FETCH' 
export const PRODUCTS_STORE = 'PRODUCTS_STORE'
export const PRODUCTS_UPDATE_STATE = 'PRODUCTS_UPDATE_STATE'

// CATEGORIES

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH' 
export const CATEGORIES_STORE = 'CATEGORIES_STORE'
export const CATEGORIES_UPDATE_STATE = 'CATEGORIES_UPDATE_STATE'

// USER

export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_ME = 'USER_ME'
export const USER_UPDATE_STATE = 'USER_UPDATE_STATE'